#Paquetes usados
library(magrittr)
library(ggside)
library(readxl)
library(stringr)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(vegan)
library(ape)
library(metR)
library(janitor)
library(openxlsx)
library(ggdendro)
library(broom.mixed)
